import { Metadata } from "next";

import { Hero } from "@/core/components/Hero/Hero";
import { Tecnologies } from "@/core/components/Technologies/Technologies";

export const metadata: Metadata = {
  title: "Home | Franzua Plasencia",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <>
      <Hero />
      <main>
        <Tecnologies />
      </main>
    </>
  );
}
